#!/usr/bin/env ruby
require 'rubygems'
require 'active_record'
require 'lib/relteq_time'
require 'lib/export-report-gen/export'
require 'app/models/simulation_batch_report'
require 'nokogiri'


DB = ActiveRecord::Base.establish_connection(
 :adapter => "sqlite3",
 :database  => Dir.pwd + "/db/development.sqlite3")


def export_simulation_batch_report id
      sbr = SimulationBatchReport.find(id)
     
      sbr.to_xml
end

puts export_simulation_batch_report 980190976
