development:
  bucket_name: 
  access_key_id:
  secret_access_key:
  max_file_size: 
  acl: 
    
test:
  bucket_name: 
  access_key_id:
  secret_access_key:
  max_file_size:
  acl:
  
production:
  bucket_name: 
  access_key_id: 
  secret_access_key:
  max_file_size: 
  acl: 
