production:
  access_key_id: AKIAJZB7YEZR7BCJCKWA
  secret_access_key: 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
  bucket: relteq-production
  cname_bucket: false

development:
  access_key_id: AKIAJZB7YEZR7BCJCKWA
  secret_access_key: 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
  bucket: relteq-development
  cname_bucket: false
